### ISSUE TITLE
ValueError: output array is read-only

### ISSUE THREAD

**Issue by yuxijin** [seanbell/intrinsic#5]
Hi, guys. I was attempting to run the decompose.py file by command 'python decompose.py test.jpg', while I got an error like the following:
`Traceback (most recent call last):
  File "decompose.py", line 125, in <module>
    r, s, decomposition = solver.solve()
  File "/home/jinyuxi/Documents/intrinsic/bell2014/solver.py", line 38, in solve
    self.initialize_intensities()
  File "/home/jinyuxi/Documents/intrinsic/bell2014/solver.py", line 105, in initialize_intensities
    samples[:, 0] *= self.params.kmeans_intensity_scale
ValueError: output array is read-only
`
I don't know why and how to fix this issue. Is there anybody can tell me what should I do?

**Comment by seanbell** [comment]
Not sure why it isn't letting you modify -- looks like the array is not writeable.  You could try changing the code to add this line before the error:
`samples = np.copy(samples)`

If that works, then a more general solution might be this code instead:
```
if not samples.flags['WRITEABLE']):
    samples = np.copy(samples)
```

**Comment by yuxijin** [comment]
Thank for your suggestion, I'll try it later.

**Comment by seanbell** [comment]
Did this solve your issue?

**Comment by yuxijin** [comment]
Yeah, it has solved the issue. Thank you very much! And I am sorry for
replying your email after so long. I was busy with other things.

Have a nice day!

Yuxi
